package com.sihai.ecps.model;

public class EbFeature {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FEATURE.FEATURE_ID
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    private Long featureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FEATURE.CAT_ID
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    private Long catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FEATURE.FEATURE_NAME
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    private String featureName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FEATURE.IS_SPEC
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    private Short isSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FEATURE.IS_SELECT
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    private Short isSelect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FEATURE.IS_SHOW
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    private Short isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FEATURE.SELECT_VALUES
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    private String selectValues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FEATURE.INPUT_TYPE
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    private Short inputType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EB_FEATURE.FEATURE_SORT
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    private Integer featureSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FEATURE.FEATURE_ID
     *
     * @return the value of EB_FEATURE.FEATURE_ID
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public Long getFeatureId() {
        return featureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FEATURE.FEATURE_ID
     *
     * @param featureId the value for EB_FEATURE.FEATURE_ID
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public void setFeatureId(Long featureId) {
        this.featureId = featureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FEATURE.CAT_ID
     *
     * @return the value of EB_FEATURE.CAT_ID
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public Long getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FEATURE.CAT_ID
     *
     * @param catId the value for EB_FEATURE.CAT_ID
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public void setCatId(Long catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FEATURE.FEATURE_NAME
     *
     * @return the value of EB_FEATURE.FEATURE_NAME
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public String getFeatureName() {
        return featureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FEATURE.FEATURE_NAME
     *
     * @param featureName the value for EB_FEATURE.FEATURE_NAME
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public void setFeatureName(String featureName) {
        this.featureName = featureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FEATURE.IS_SPEC
     *
     * @return the value of EB_FEATURE.IS_SPEC
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public Short getIsSpec() {
        return isSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FEATURE.IS_SPEC
     *
     * @param isSpec the value for EB_FEATURE.IS_SPEC
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public void setIsSpec(Short isSpec) {
        this.isSpec = isSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FEATURE.IS_SELECT
     *
     * @return the value of EB_FEATURE.IS_SELECT
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public Short getIsSelect() {
        return isSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FEATURE.IS_SELECT
     *
     * @param isSelect the value for EB_FEATURE.IS_SELECT
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public void setIsSelect(Short isSelect) {
        this.isSelect = isSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FEATURE.IS_SHOW
     *
     * @return the value of EB_FEATURE.IS_SHOW
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public Short getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FEATURE.IS_SHOW
     *
     * @param isShow the value for EB_FEATURE.IS_SHOW
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public void setIsShow(Short isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FEATURE.SELECT_VALUES
     *
     * @return the value of EB_FEATURE.SELECT_VALUES
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public String getSelectValues() {
        return selectValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FEATURE.SELECT_VALUES
     *
     * @param selectValues the value for EB_FEATURE.SELECT_VALUES
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public void setSelectValues(String selectValues) {
        this.selectValues = selectValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FEATURE.INPUT_TYPE
     *
     * @return the value of EB_FEATURE.INPUT_TYPE
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public Short getInputType() {
        return inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FEATURE.INPUT_TYPE
     *
     * @param inputType the value for EB_FEATURE.INPUT_TYPE
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public void setInputType(Short inputType) {
        this.inputType = inputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EB_FEATURE.FEATURE_SORT
     *
     * @return the value of EB_FEATURE.FEATURE_SORT
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public Integer getFeatureSort() {
        return featureSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EB_FEATURE.FEATURE_SORT
     *
     * @param featureSort the value for EB_FEATURE.FEATURE_SORT
     *
     * @mbggenerated Fri Feb 24 17:51:46 CST 2017
     */
    public void setFeatureSort(Integer featureSort) {
        this.featureSort = featureSort;
    }
}