package com.sihai.ecps.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-03-09T17:24:32.664+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://service.ws.ecps.sihai.com/", name = "EbWsItemService")
@XmlSeeAlso({ObjectFactory.class})
public interface EbWsItemService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "publishItem", targetNamespace = "http://service.ws.ecps.sihai.com/", className = "com.sihai.ecps.ws.service.PublishItem")
    @WebMethod
    @ResponseWrapper(localName = "publishItemResponse", targetNamespace = "http://service.ws.ecps.sihai.com/", className = "com.sihai.ecps.ws.service.PublishItemResponse")
    public java.lang.String publishItem(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
